language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
before_script:
  - pip install -U -r test_requirements.txt
script:
  - py.test --doctest-modules --pep8 rtkit -v --cov rtkit --cov-report term-missing
after_success:
  - pip install python-coveralls
  - coveralls
